EMBED_MODEL_ID = "sentence-transformers/all-MiniLM-L6-v2"
PINECONE_EMBEDDING_MODEL = "llama-text-embed-v2"
PINECONE_INDEX_NAME = "datasmith"
PINECONE_RERANKER_MODEL = "bge-reranker-v2-m3"
PINECONE_NAMESPACE = "nephrology"
